clear; clc; close all;
% LIVELINK_PARAMETER_SWEEP_POSTPROCESS
%
% Post-process saved Module 04 parameter-sweep results without rerunning
% COMSOL.
%
% Supported result formats:
%
%   Format A: bound-mode sweep
%       Generated by:
%           livelink_parameter_sweep_bound_modes.m
%       Expected variables:
%           cfg, results
%
%   Format B: single-mode predefined-integral sweep
%       Generated by older versions of:
%           livelink_parameter_sweep_with_integral.m
%       Expected variables:
%           cfg, valueMat, success, message, runtime_s
%
%   Format C: all-mode predefined-integral sweep
%       Generated by the current:
%           livelink_parameter_sweep_with_integral.m
%       Expected variables:
%           cfg, results
%
% The script automatically detects the saved result format.

%% ===================== 1. User configuration =====================

scriptDir = fileparts(mfilename('fullpath'));
repoRoot  = fileparts(scriptDir);

cfgPost = struct();

% Choose which result format to post-process.
%
% Options:
%   'auto'
%       Automatically detect the result format from sweep_raw.mat.
%
%   'bound_modes'
%       Post-process results from:
%           livelink_parameter_sweep_bound_modes.m
%
%   'integral_all_modes'
%       Post-process results from:
%           livelink_parameter_sweep_with_integral.m
%       when it saves all returned modes.
%
cfgPost.resultFormat = 'integral_all_modes';

% Leave empty to automatically use the newest output folder matching
% cfgPost.resultFormat. Or manually set a specific folder path.
cfgPost.resultDir = '';

% Optional thresholds for bound-mode post-processing.
% These are only used when cfgPost.resultFormat = 'bound_modes'.
cfgPost.useLossThreshold  = true;
cfgPost.maxLoss_dB_per_cm = 10;

cfgPost.useQThreshold = false;
cfgPost.minQ_est      = 1e5;

cfgPost.sortAcceptedBy = 'real_neff_descend';

% Plot settings for integral all-mode results.
cfgPost.plotIntegralNeffVsWidth = true;
cfgPost.plotIntegralLossVsWidth = true;
cfgPost.plotIntegralLossVsFrac  = true;

% Name of the predefined field-fraction variable to compare with loss.
cfgPost.fracExprForPlot = 'frac_E2_LN';

% Plot settings for old single-mode integral-sweep results.
cfgPost.plotIntegralRealParts = true;
cfgPost.plotIntegralImagParts = false;
%% ===================== 2. Locate and load sweep result =====================

if isempty(cfgPost.resultDir)
    outputRoot = fullfile(repoRoot, 'local_outputs');
    folderPatterns = get_output_folder_patterns(cfgPost.resultFormat);

    cfgPost.resultDir = find_newest_sweep_folder_multi( ...
        outputRoot, folderPatterns);
end

rawMatFile = fullfile(cfgPost.resultDir, 'sweep_raw.mat');

fprintf('Loading sweep result:\n%s\n\n', rawMatFile);

loaded = load(rawMatFile);

resultFormat = lower(string(cfgPost.resultFormat));

if resultFormat == "auto"
    resultFormat = infer_result_format(loaded);
end

switch resultFormat
    case "bound_modes"
        fprintf('Selected result format: bound-mode sweep.\n\n');
        postprocess_bound_mode_sweep(loaded, cfgPost);

    case "integral_all_modes"
        fprintf('Selected result format: all-mode predefined-integral sweep.\n\n');
        postprocess_all_mode_integral_sweep(loaded, cfgPost);

    case "integral_single_mode"
        fprintf('Selected result format: single-mode predefined-integral sweep.\n\n');
        postprocess_single_mode_integral_sweep(loaded, cfgPost);

    otherwise
        error('LiveLinkSweep:UnknownResultFormat', ...
            'Unknown cfgPost.resultFormat: %s', resultFormat);
end

%% ===================== Local helper functions =====================

function tf = is_all_mode_integral_results(loaded)
%IS_ALL_MODE_INTEGRAL_RESULTS Detect current integral all-mode format.

    tf = false;

    if ~isfield(loaded, 'results') || isempty(loaded.results)
        return;
    end

    requiredFields = {'valueMat', 'exprList', 'numModes'};
    tf = all(isfield(loaded.results, requiredFields));
end

function resultDir = find_newest_sweep_folder_multi(outputRoot, patternList)
%FIND_NEWEST_SWEEP_FOLDER_MULTI Find newest output folder matching patterns.

    allFolders = [];

    for kk = 1:numel(patternList)
        thisList = dir(fullfile(outputRoot, patternList{kk}));
        thisList = thisList([thisList.isdir]);
        allFolders = [allFolders; thisList(:)]; %#ok<AGROW>
    end

    if isempty(allFolders)
        error('LiveLinkSweep:NoOutputFolder', ...
            'No sweep output folder found in: %s', outputRoot);
    end

    [~, idx] = max([allFolders.datenum]);
    resultDir = fullfile(allFolders(idx).folder, allFolders(idx).name);
end

function postprocess_all_mode_integral_sweep(loaded, cfgPost)
%POSTPROCESS_ALL_MODE_INTEGRAL_SWEEP Plot and export all-mode integral data.

    cfg = loaded.cfg;
    results = loaded.results;

    allModeTable = make_all_mode_integral_table_post(results);

    if isempty(allModeTable)
        error('LiveLinkSweep:EmptyAllModeTable', ...
            'No successful all-mode integral results were found.');
    end

    allModeCsvFile = fullfile( ...
        cfgPost.resultDir, 'sweep_all_modes_postprocessed.csv');
    writetable(allModeTable, allModeCsvFile);

    figure;
    plot(allModeTable.w_um, allModeTable.neff_real, '.', ...
        'MarkerSize', 10);
    grid on;
    xlabel('Waveguide width (\mum)');
    ylabel('real(n_{eff})');
    title('All returned modes');

    figure;
    semilogy(allModeTable.w_um, allModeTable.loss_dB_per_cm, '.', ...
        'MarkerSize', 10);
    grid on;
    xlabel('Waveguide width (\mum)');
    ylabel('Loss estimated from imag(n_{eff}) (dB/cm)');
    title('All returned modes: loss estimate');

    if isfield(cfg, 'fracExprForQuickPlot')
        fracName = matlab.lang.makeValidName(cfg.fracExprForQuickPlot);
    else
        fracName = 'frac_E2_LN';
    end

    fracRealName = [fracName, '_real'];

    if ismember(fracRealName, allModeTable.Properties.VariableNames)
        figure;
        semilogx(allModeTable.loss_dB_per_cm, ...
            allModeTable.(fracRealName), '.', ...
            'MarkerSize', 10);
        grid on;
        xlabel('Loss estimated from imag(n_{eff}) (dB/cm)');
        ylabel(strrep(fracName, '_', '\_'));
        title('Bound-mode indicators: loss versus predefined field fraction');
    end

    fprintf('All-mode integral table saved to:\n%s\n', allModeCsvFile);
end

function T = make_all_mode_integral_table_post(results)
%MAKE_ALL_MODE_INTEGRAL_TABLE_POST Create one table row per mode.

    T = table();

    for jj = 1:numel(results)
        if ~results(jj).success || isempty(results(jj).valueMat)
            continue;
        end

        numModes = results(jj).numModes;

        thisT = table( ...
            repmat(jj, numModes, 1), ...
            repmat(results(jj).w_um, numModes, 1), ...
            results(jj).modeIndex(:), ...
            real(results(jj).neff_all(:)), ...
            imag(results(jj).neff_all(:)), ...
            results(jj).loss_dB_per_cm_all(:), ...
            results(jj).Q_est_all(:), ...
            'VariableNames', { ...
                'sweep_index', ...
                'w_um', ...
                'mode_index', ...
                'neff_real', ...
                'neff_imag', ...
                'loss_dB_per_cm', ...
                'Q_est'});

        exprList = results(jj).exprList(:);
        valueMat = results(jj).valueMat;

        for kk = 1:numel(exprList)
            baseName = matlab.lang.makeValidName(exprList{kk});
            thisT.([baseName, '_real']) = real(valueMat(:, kk));
            thisT.([baseName, '_imag']) = imag(valueMat(:, kk));
        end

        T = [T; thisT]; %#ok<AGROW>
    end
end

function postprocess_bound_mode_sweep(loaded, cfgPost)
%POSTPROCESS_BOUND_MODE_SWEEP Re-apply bound-mode filtering and plot results.

    results = loaded.results;

    numSweepPoints = numel(results);

    w_um = NaN(numSweepPoints, 1);
    selected_neff = NaN(numSweepPoints, 1);
    selected_loss_dB_per_cm = NaN(numSweepPoints, 1);
    selected_Q_est = NaN(numSweepPoints, 1);
    numAccepted = NaN(numSweepPoints, 1);

    all_w = zeros(0, 1);
    all_mode_index = zeros(0, 1);
    all_neff_real = zeros(0, 1);
    all_neff_imag = zeros(0, 1);
    all_loss = zeros(0, 1);
    all_Q = zeros(0, 1);
    all_isAccepted = false(0, 1);

    for ii = 1:numSweepPoints
        w_um(ii) = results(ii).w_um;

        if ~results(ii).success || isempty(results(ii).neff_all)
            continue;
        end

        neff_all = results(ii).neff_all(:);
        loss_all = results(ii).loss_dB_per_cm_all(:);
        Q_all = results(ii).Q_est_all(:);

        numModes = numel(neff_all);

        accepted_idx = select_bound_modes_post( ...
            neff_all, loss_all, Q_all, cfgPost);

        accepted_idx = sort_accepted_modes_post( ...
            accepted_idx, neff_all, loss_all, Q_all, cfgPost);

        numAccepted(ii) = numel(accepted_idx);

        if ~isempty(accepted_idx)
            firstAccepted = accepted_idx(1);
            selected_neff(ii) = neff_all(firstAccepted);
            selected_loss_dB_per_cm(ii) = loss_all(firstAccepted);
            selected_Q_est(ii) = Q_all(firstAccepted);
        end

        acceptedMask = false(numModes, 1);
        acceptedMask(accepted_idx) = true;

        all_w = [all_w; repmat(w_um(ii), numModes, 1)]; %#ok<AGROW>
        all_mode_index = [all_mode_index; (1:numModes).']; %#ok<AGROW>
        all_neff_real = [all_neff_real; real(neff_all)]; %#ok<AGROW>
        all_neff_imag = [all_neff_imag; imag(neff_all)]; %#ok<AGROW>
        all_loss = [all_loss; loss_all]; %#ok<AGROW>
        all_Q = [all_Q; Q_all]; %#ok<AGROW>
        all_isAccepted = [all_isAccepted; acceptedMask]; %#ok<AGROW>
    end

    all_w = all_w(:);
    all_mode_index = all_mode_index(:);
    all_neff_real = all_neff_real(:);
    all_neff_imag = all_neff_imag(:);
    all_loss = all_loss(:);
    all_Q = all_Q(:);
    all_isAccepted = logical(all_isAccepted(:));

    figure;
    plot(w_um, real(selected_neff), 'o-', 'LineWidth', 1.5);
    grid on;
    xlabel('Waveguide width (\mum)');
    ylabel('Selected real(n_{eff})');
    title('Selected bound mode after threshold filtering');

    figure;
    semilogy(w_um, selected_loss_dB_per_cm, 'o-', 'LineWidth', 1.5);
    grid on;
    xlabel('Waveguide width (\mum)');
    ylabel('Selected loss (dB/cm)');
    title('Selected mode propagation loss');

    figure;
    hold on;
    rejectedMask = ~all_isAccepted;
    acceptedMask = all_isAccepted;

    if any(rejectedMask)
        plot(all_w(rejectedMask), all_neff_real(rejectedMask), '.', ...
            'MarkerSize', 10);
    end

    if any(acceptedMask)
        plot(all_w(acceptedMask), all_neff_real(acceptedMask), 'o', ...
            'MarkerSize', 6);
    end

    grid on;
    xlabel('Waveguide width (\mum)');
    ylabel('real(n_{eff})');
    title('All returned modes and accepted modes');
    legend('Rejected modes', 'Accepted modes', 'Location', 'best');
    hold off;

    summaryTable = table( ...
        w_um, ...
        numAccepted, ...
        real(selected_neff), ...
        imag(selected_neff), ...
        selected_loss_dB_per_cm, ...
        selected_Q_est, ...
        'VariableNames', { ...
            'w_um', ...
            'numAccepted', ...
            'selected_neff_real', ...
            'selected_neff_imag', ...
            'selected_loss_dB_per_cm', ...
            'selected_Q_est'});

    allModesTable = table( ...
        all_w, ...
        all_mode_index, ...
        all_neff_real, ...
        all_neff_imag, ...
        all_loss, ...
        all_Q, ...
        all_isAccepted, ...
        'VariableNames', { ...
            'w_um', ...
            'mode_index', ...
            'neff_real', ...
            'neff_imag', ...
            'loss_dB_per_cm', ...
            'Q_est', ...
            'isAccepted'});

    postCsvFile = fullfile( ...
        cfgPost.resultDir, 'sweep_summary_postprocessed.csv');

    allModesCsvFile = fullfile( ...
        cfgPost.resultDir, 'sweep_all_modes_postprocessed.csv');

    writetable(summaryTable, postCsvFile);
    writetable(allModesTable, allModesCsvFile);

    fprintf('Post-processing summary saved to:\n%s\n', postCsvFile);
    fprintf('All-mode post-processing table saved to:\n%s\n', allModesCsvFile);
end

function postprocess_single_mode_integral_sweep(loaded, cfgPost)
%POSTPROCESS_SINGLE_MODE_INTEGRAL_SWEEP Post-process old valueMat format.

    cfg = loaded.cfg;
    valueMat = loaded.valueMat;

    if isfield(loaded, 'success')
        success = loaded.success(:);
    else
        success = true(size(valueMat, 1), 1);
    end

    if isfield(loaded, 'message')
        message = loaded.message(:);
    else
        message = strings(size(valueMat, 1), 1);
    end

    if isfield(loaded, 'runtime_s')
        runtime_s = loaded.runtime_s(:);
    else
        runtime_s = NaN(size(valueMat, 1), 1);
    end

    if isfield(cfg, 'wList_um')
        w_um = cfg.wList_um(:);
    else
        w_um = (1:size(valueMat, 1)).';
        warning('LiveLinkSweep:MissingSweepAxis', ...
            ['cfg.wList_um is not found. ', ...
             'Using sweep-point index as the x axis.']);
    end

    if isfield(cfg, 'resultExprList')
        exprList = cfg.resultExprList(:);
    else
        exprList = make_default_expr_list(size(valueMat, 2));
        warning('LiveLinkSweep:MissingExprList', ...
            ['cfg.resultExprList is not found. ', ...
             'Using generic expression names.']);
    end

    summaryTable = make_single_mode_integral_summary_table( ...
        w_um, exprList, valueMat, success, message, runtime_s);

    if cfgPost.plotIntegralRealParts
        figure;
        hold on;

        for kk = 1:numel(exprList)
            plot(w_um, real(valueMat(:, kk)), 'o-', 'LineWidth', 1.5);
        end

        grid on;
        xlabel('Waveguide width (\mum)');
        ylabel('Real part');
        title('Predefined scalar/integral results: real parts');
        legend(make_legend_labels(exprList, 'real'), ...
            'Location', 'best', 'Interpreter', 'none');
        hold off;
    end

    if cfgPost.plotIntegralImagParts
        figure;
        hold on;

        for kk = 1:numel(exprList)
            plot(w_um, imag(valueMat(:, kk)), 'o-', 'LineWidth', 1.5);
        end

        grid on;
        xlabel('Waveguide width (\mum)');
        ylabel('Imaginary part');
        title('Predefined scalar/integral results: imaginary parts');
        legend(make_legend_labels(exprList, 'imag'), ...
            'Location', 'best', 'Interpreter', 'none');
        hold off;
    end

    postCsvFile = fullfile( ...
        cfgPost.resultDir, 'sweep_summary_postprocessed.csv');

    writetable(summaryTable, postCsvFile);

    fprintf('Single-mode integral summary saved to:\n%s\n', postCsvFile);
end

function accepted_idx = select_bound_modes_post(neff, loss_dB_per_cm, Q_est, cfgPost)
%SELECT_BOUND_MODES_POST Re-apply bound-mode thresholds.

    valid = isfinite(real(neff)) & isfinite(imag(neff));

    if cfgPost.useLossThreshold
        valid = valid & (loss_dB_per_cm <= cfgPost.maxLoss_dB_per_cm);
    end

    if cfgPost.useQThreshold
        valid = valid & (Q_est >= cfgPost.minQ_est);
    end

    accepted_idx = find(valid);
end

function accepted_idx = sort_accepted_modes_post( ...
    accepted_idx, neff, loss_dB_per_cm, Q_est, cfgPost)
%SORT_ACCEPTED_MODES_POST Sort accepted modes.

    if isempty(accepted_idx)
        return;
    end

    switch lower(cfgPost.sortAcceptedBy)
        case 'real_neff_descend'
            [~, order] = sort(real(neff(accepted_idx)), 'descend');

        case 'loss_ascend'
            [~, order] = sort(loss_dB_per_cm(accepted_idx), 'ascend');

        case 'q_descend'
            [~, order] = sort(Q_est(accepted_idx), 'descend');

        otherwise
            order = 1:numel(accepted_idx);
    end

    accepted_idx = accepted_idx(order);
end

function T = make_single_mode_integral_summary_table( ...
    w_um, exprList, valueMat, success, message, runtime_s)
%MAKE_SINGLE_MODE_INTEGRAL_SUMMARY_TABLE Create table with real/imag cols.

    N = numel(w_um);

    T = table( ...
        (1:N).', ...
        w_um(:), ...
        success(:), ...
        runtime_s(:), ...
        message(:), ...
        'VariableNames', { ...
            'index', ...
            'w_um', ...
            'success', ...
            'runtime_s', ...
            'message'});

    for kk = 1:numel(exprList)
        baseName = matlab.lang.makeValidName(exprList{kk});
        T.([baseName, '_real']) = real(valueMat(:, kk));
        T.([baseName, '_imag']) = imag(valueMat(:, kk));
    end
end

function exprList = make_default_expr_list(numExpr)
%MAKE_DEFAULT_EXPR_LIST Make generic expression names.

    exprList = cell(numExpr, 1);

    for kk = 1:numExpr
        exprList{kk} = sprintf('expr_%02d', kk);
    end
end

function labels = make_legend_labels(exprList, partName)
%MAKE_LEGEND_LABELS Make readable legend labels.

    labels = cell(numel(exprList), 1);

    for kk = 1:numel(exprList)
        labels{kk} = sprintf('%s %s', exprList{kk}, partName);
    end
end

function folderPatterns = get_output_folder_patterns(resultFormat)
%GET_OUTPUT_FOLDER_PATTERNS Return output-folder patterns for one format.

    switch lower(string(resultFormat))
        case "bound_modes"
            folderPatterns = {'waveguide_width_bound_mode_sweep_*'};

        case "integral_all_modes"
            folderPatterns = {'waveguide_width_sweep_with_integral_all_modes_*'};

        case "integral_single_mode"
            folderPatterns = {'waveguide_width_sweep_with_integral_*'};

        case "auto"
            folderPatterns = { ...
                'waveguide_width_bound_mode_sweep_*', ...
                'waveguide_width_sweep_with_integral_all_modes_*', ...
                'waveguide_width_sweep_with_integral_*', ...
                'waveguide_width_sweep_*'};

        otherwise
            error('LiveLinkSweep:UnknownResultFormat', ...
                'Unknown result format: %s', resultFormat);
    end
end

function resultFormat = infer_result_format(loaded)
%INFER_RESULT_FORMAT Infer sweep result format from variables in sweep_raw.mat.

    if isfield(loaded, 'results') && is_all_mode_integral_results(loaded)
        resultFormat = "integral_all_modes";

    elseif isfield(loaded, 'results')
        resultFormat = "bound_modes";

    elseif isfield(loaded, 'valueMat')
        resultFormat = "integral_single_mode";

    else
        error('LiveLinkSweep:UnknownResultFormat', ...
            ['Cannot infer result format. Expected one of:\n', ...
             '  1. results struct from bound-mode sweep\n', ...
             '  2. results struct with valueMat from all-mode integral sweep\n', ...
             '  3. valueMat from single-mode integral sweep']);
    end
end