clear; clc; close all;

% LIVELINK_PARAMETER_SWEEP_POSTPROCESS
%
% Goal:
%   Load saved parameter-sweep results and post-process accepted bound modes
%   without rerunning COMSOL.
%
% This script assumes the sweep was generated by:
%   livelink_parameter_sweep_bound_modes.m

%% ===================== 1. User configuration =====================

scriptDir = fileparts(mfilename('fullpath'));
repoRoot  = fileparts(scriptDir);

cfgPost = struct();

% Leave empty to automatically use the newest sweep folder.
cfgPost.resultDir = '';

% Optional new thresholds for post-processing.
% This demonstrates why saving all raw modes is useful.
cfgPost.useLossThreshold  = true;
cfgPost.maxLoss_dB_per_cm = 10;

cfgPost.useQThreshold = false;
cfgPost.minQ_est      = 1e5;

cfgPost.sortAcceptedBy = 'real_neff_descend';

%% ===================== 2. Locate and load sweep result =====================

if isempty(cfgPost.resultDir)
    outputRoot = fullfile(repoRoot, 'local_outputs');
    cfgPost.resultDir = findNewestSweepFolder( ...
        outputRoot, 'waveguide_width_bound_mode_sweep_*');
end

rawMatFile = fullfile(cfgPost.resultDir, 'sweep_raw.mat');

fprintf('Loading sweep result:\n%s\n\n', rawMatFile);
loaded = load(rawMatFile, 'cfg', 'results');

cfg = loaded.cfg; %#ok<NASGU>
results = loaded.results;

%% ===================== 3. Re-apply thresholds without rerunning COMSOL =====================

numSweepPoints = numel(results);

w_um = NaN(numSweepPoints, 1);
selected_neff = NaN(numSweepPoints, 1);
selected_loss_dB_per_cm = NaN(numSweepPoints, 1);
selected_Q_est = NaN(numSweepPoints, 1);
numAccepted = NaN(numSweepPoints, 1);

% Flattened arrays for plotting all returned modes.
all_w = zeros(0, 1);
all_mode_index = zeros(0, 1);
all_neff_real = zeros(0, 1);
all_neff_imag = zeros(0, 1);
all_loss = zeros(0, 1);
all_Q = zeros(0, 1);
all_isAccepted = false(0, 1);

for ii = 1:numSweepPoints
    w_um(ii) = results(ii).w_um;

    if ~results(ii).success || isempty(results(ii).neff_all)
        continue;
    end

    neff_all = results(ii).neff_all(:);
    loss_all = results(ii).loss_dB_per_cm_all(:);
    Q_all = results(ii).Q_est_all(:);
    numModes = numel(neff_all);

    accepted_idx = selectBoundModesPost(neff_all, loss_all, Q_all, cfgPost);
    accepted_idx = sortAcceptedModesPost( ...
        accepted_idx, neff_all, loss_all, Q_all, cfgPost);

    numAccepted(ii) = numel(accepted_idx);

    if ~isempty(accepted_idx)
        firstAccepted = accepted_idx(1);
        selected_neff(ii) = neff_all(firstAccepted);
        selected_loss_dB_per_cm(ii) = loss_all(firstAccepted);
        selected_Q_est(ii) = Q_all(firstAccepted);
    end

    acceptedMask = false(numModes, 1);
    acceptedMask(accepted_idx) = true;

    all_w = [all_w; repmat(w_um(ii), numModes, 1)]; %#ok<AGROW>
    all_mode_index = [all_mode_index; (1:numModes).']; %#ok<AGROW>
    all_neff_real = [all_neff_real; real(neff_all)]; %#ok<AGROW>
    all_neff_imag = [all_neff_imag; imag(neff_all)]; %#ok<AGROW>
    all_loss = [all_loss; loss_all]; %#ok<AGROW>
    all_Q = [all_Q; Q_all]; %#ok<AGROW>
    all_isAccepted = [all_isAccepted; acceptedMask]; %#ok<AGROW>
end

% Make the plotting index robust, even if this section was run manually.
all_w = all_w(:);
all_neff_real = all_neff_real(:);
all_loss = all_loss(:);
all_isAccepted = logical(all_isAccepted(:));

numAllModes = numel(all_w);
if any([numel(all_neff_real), numel(all_loss), numel(all_isAccepted)] ~= numAllModes)
    error('LiveLinkSweep:PostprocessLengthMismatch', ...
        ['The flattened mode arrays have inconsistent lengths. ', ...
        'Run the whole post-processing script from the beginning.']);
end

%% ===================== 4. Plot selected bound-mode result =====================

figure;
plot(w_um, real(selected_neff), 'o-', 'LineWidth', 1.5);
grid on;
xlabel('Waveguide width (\mum)');
ylabel('Selected real(n_{eff})');
title('Selected bound mode after threshold filtering');

figure;
semilogy(w_um, selected_loss_dB_per_cm, 'o-', 'LineWidth', 1.5);
grid on;
xlabel('Waveguide width (\mum)');
ylabel('Selected loss (dB/cm)');
title('Selected mode propagation loss');

figure;
hold on;
rejectedMask = ~all_isAccepted;
acceptedMask = all_isAccepted;

if any(rejectedMask)
    plot(all_w(rejectedMask), all_neff_real(rejectedMask), '.', ...
        'MarkerSize', 10);
end

if any(acceptedMask)
    plot(all_w(acceptedMask), all_neff_real(acceptedMask), 'o', ...
        'MarkerSize', 6);
end

grid on;
xlabel('Waveguide width (\mum)');
ylabel('real(n_{eff})');
title('All returned modes and accepted modes');
legend('Rejected modes', 'Accepted modes', 'Location', 'best');
hold off;

%% ===================== 5. Export updated post-processing summary =====================

summaryTable = table( ...
    w_um, ...
    numAccepted, ...
    real(selected_neff), ...
    imag(selected_neff), ...
    selected_loss_dB_per_cm, ...
    selected_Q_est, ...
    'VariableNames', { ...
    'w_um', ...
    'numAccepted', ...
    'selected_neff_real', ...
    'selected_neff_imag', ...
    'selected_loss_dB_per_cm', ...
    'selected_Q_est'});

allModesTable = table( ...
    all_w, ...
    all_mode_index, ...
    all_neff_real, ...
    all_neff_imag, ...
    all_loss, ...
    all_Q, ...
    all_isAccepted, ...
    'VariableNames', { ...
    'w_um', ...
    'mode_index', ...
    'neff_real', ...
    'neff_imag', ...
    'loss_dB_per_cm', ...
    'Q_est', ...
    'isAccepted'});

postCsvFile = fullfile(cfgPost.resultDir, 'sweep_summary_postprocessed.csv');
allModesCsvFile = fullfile(cfgPost.resultDir, 'sweep_all_modes_postprocessed.csv');

writetable(summaryTable, postCsvFile);
writetable(allModesTable, allModesCsvFile);

fprintf('Post-processing summary saved to:\n%s\n', postCsvFile);
fprintf('All-mode post-processing table saved to:\n%s\n', allModesCsvFile);

%% ===================== Local helper functions =====================

function resultDir = findNewestSweepFolder(outputRoot, pattern)
%FINDNEWESTSWEEPFOLDER Find newest output folder matching a pattern.

    folderList = dir(fullfile(outputRoot, pattern));
    folderList = folderList([folderList.isdir]);

    if isempty(folderList)
        error('LiveLinkSweep:NoOutputFolder', ...
            'No sweep output folder found in: %s', outputRoot);
    end

    [~, idx] = max([folderList.datenum]);
    resultDir = fullfile(folderList(idx).folder, folderList(idx).name);
end

function accepted_idx = selectBoundModesPost(neff, loss_dB_per_cm, Q_est, cfgPost)
%SELECTBOUNDMODESPOST Re-apply bound-mode thresholds.

    valid = isfinite(real(neff)) & isfinite(imag(neff));

    if cfgPost.useLossThreshold
        valid = valid & (loss_dB_per_cm <= cfgPost.maxLoss_dB_per_cm);
    end

    if cfgPost.useQThreshold
        valid = valid & (Q_est >= cfgPost.minQ_est);
    end

    accepted_idx = find(valid);
end

function accepted_idx = sortAcceptedModesPost( ...
    accepted_idx, neff, loss_dB_per_cm, Q_est, cfgPost)
%SORTACCEPTEDMODESPOST Sort accepted modes.

    if isempty(accepted_idx)
        return;
    end

    switch lower(cfgPost.sortAcceptedBy)
        case 'real_neff_descend'
            [~, order] = sort(real(neff(accepted_idx)), 'descend');

        case 'loss_ascend'
            [~, order] = sort(loss_dB_per_cm(accepted_idx), 'ascend');

        case 'q_descend'
            [~, order] = sort(Q_est(accepted_idx), 'descend');

        otherwise
            order = 1:numel(accepted_idx);
    end

    accepted_idx = accepted_idx(order);
end
