%% LiveLink Module 05A: Mode-family component-ratio extraction
%
% This is a COMSOL-run / data-extraction script.
% It does NOT make figures.
%
% Goals:
%   1. Define Ex/Ey/Ez integral variables in COMSOL using MATLAB LiveLink.
%   2. Sweep a waveguide parameter.
%   3. Read all returned modes.
%   4. Filter bound modes using loss/Q thresholds.
%   5. Save accepted mode-family metrics for later post-processing.
%
% Main output:
%   mode_family_metrics.csv      accepted modes only
%   mode_family_all_modes.csv    all returned modes, optional
%
% Post-processing:
%   Use livelink_mode_family_component_postprocess.m.

clear; clc; close all;

%% ===================== 1. User configuration =====================
thisFile = mfilename('fullpath');
if isempty(thisFile)
    templateDir = pwd;
else
    templateDir = fileparts(thisFile);
end
repoRoot = fileparts(templateDir);

cfg = struct();

% COMSOL model and tags
cfg.modelFile    = fullfile(repoRoot, 'examples', 'LN_ridge_waveguide_Zcut.mph');
cfg.componentTag = 'comp1';
cfg.studyTag     = 'std1';
cfg.datasetTag   = 'dset1';

% Parameter sweep
cfg.paramName = 'w_ln';
cfg.paramUnit = 'um';
cfg.wList_um  = linspace(0.8, 1.4, 13);

% Number of solved modes.
% In COMSOL, set the mode-analysis "Desired number of modes" field to the
% global parameter name below, for example: Nmode.
cfg.setNmodeParam = true;
cfg.NmodeParamName = 'Nmode';
cfg.Nmode = 10;

% Optical wavelength used to estimate loss from imag(neff)
cfg.lambda0_um = 1.55;

% Bound-mode filtering
cfg.useLossThreshold  = true;
cfg.maxLoss_dB_per_cm = 10;

cfg.useQThreshold = false;
cfg.minQ_est      = 1e5;

% Save all modes for debugging, in addition to accepted modes.
cfg.saveAllModesCsv = true;

% COMSOL expressions
cfg.neffExpr = 'ewfd.neff';
cfg.ExExpr = 'ewfd.Ex';
cfg.EyExpr = 'ewfd.Ey';
cfg.EzExpr = 'ewfd.Ez';

% Existing COMSOL integration operator.
% The current teaching model contains intop_LN_physical for the LN physical
% region. Change this if another physical region should be used.
cfg.intopName = 'intop_LN_physical';

% LiveLink-defined variable group
cfg.variableTag   = 'var_mode_family';
cfg.variableLabel = 'Mode-family metrics generated by MATLAB LiveLink';

% Mode-family label threshold
cfg.minDominantFraction = 0.80;

% Optional: save a modified .mph copy containing the generated variables.
cfg.saveModelWithVariables = false;
cfg.modifiedModelFile = fullfile(repoRoot, 'examples', ...
    'LN_ridge_waveguide_Zcut_with_mode_family_vars.mph');

% Output
cfg.outputRoot = fullfile(repoRoot, 'local_outputs');
timestamp = char(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
cfg.runName = ['mode_family_component_ratio_', timestamp];
cfg.outputDir = fullfile(cfg.outputRoot, cfg.runName);
cfg.saveAfterEachSweepPoint = true;

%% ===================== 2. Prepare output folder =====================
if ~exist(cfg.outputDir, 'dir')
    mkdir(cfg.outputDir);
end
save(fullfile(cfg.outputDir, 'mode_family_config.mat'), 'cfg');

%% ===================== 3. Load COMSOL model =====================
if exist(cfg.modelFile, 'file') ~= 2
    error('ModeFamily:ModelFileNotFound', ...
        ['COMSOL model file not found:\n  %s\n\n', ...
         'Please update cfg.modelFile.'], cfg.modelFile);
end

fprintf('Loading COMSOL model:\n  %s\n', cfg.modelFile);
model = mphload(cfg.modelFile);

%% ===================== 4. Define variables and set Nmode =====================
model = ensure_mode_family_variables(model, cfg);

if cfg.setNmodeParam
    model.param.set(cfg.NmodeParamName, sprintf('%d', cfg.Nmode));
    fprintf('Set number-of-modes parameter: %s = %d\n', ...
        cfg.NmodeParamName, cfg.Nmode);
end

if cfg.saveModelWithVariables
    fprintf('Saving modified model with LiveLink-defined variables:\n  %s\n', ...
        cfg.modifiedModelFile);
    mphsave(model, cfg.modifiedModelFile);
end

%% ===================== 5. Run sweep =====================
numSweepPoints = numel(cfg.wList_um);

allModeTable = table();
acceptedModeTable = table();
pointSummaryTable = table();

fprintf('\nStarting mode-family component-ratio sweep.\n');
fprintf('Number of sweep points: %d\n', numSweepPoints);
fprintf('Requested number of modes: %d\n', cfg.Nmode);
fprintf('Integration operator: %s\n', cfg.intopName);
fprintf('Loss threshold enabled: %d, max loss = %.6g dB/cm\n\n', ...
    cfg.useLossThreshold, cfg.maxLoss_dB_per_cm);

for jj = 1:numSweepPoints
    w_um = cfg.wList_um(jj);
    tStart = tic;

    fprintf('[%d/%d] %s = %.6g %s\n', ...
        jj, numSweepPoints, cfg.paramName, w_um, cfg.paramUnit);

    success = false;
    message = "OK";
    numModes = 0;
    numAccepted = 0;

    try
        model.param.set(cfg.paramName, ...
            sprintf('%.12g[%s]', w_um, cfg.paramUnit));

        if cfg.setNmodeParam
            model.param.set(cfg.NmodeParamName, sprintf('%d', cfg.Nmode));
        end

        model.study(cfg.studyTag).run;

        thisAllTable = read_mode_family_table(model, cfg, jj, w_um);
        numModes = height(thisAllTable);

        thisAllTable.isAccepted = apply_bound_mode_filter( ...
            thisAllTable.neff_real + 1i*thisAllTable.neff_imag, ...
            thisAllTable.loss_dB_per_cm, ...
            thisAllTable.Q_est, ...
            cfg);

        thisAcceptedTable = thisAllTable(thisAllTable.isAccepted, :);
        numAccepted = height(thisAcceptedTable);

        allModeTable = [allModeTable; thisAllTable]; %#ok<AGROW>
        acceptedModeTable = [acceptedModeTable; thisAcceptedTable]; %#ok<AGROW>

        success = true;

        fprintf('  Returned modes: %d\n', numModes);
        fprintf('  Accepted modes: %d\n', numAccepted);

        if numAccepted > 0
            fprintf('  accepted loss range: %.6g to %.6g dB/cm\n', ...
                min(thisAcceptedTable.loss_dB_per_cm), ...
                max(thisAcceptedTable.loss_dB_per_cm));
        else
            fprintf('  no mode passed the current filter.\n');
        end

        fprintf('  done. time = %.2f s\n\n', toc(tStart));

    catch ME
        success = false;
        message = string(ME.message);

        warning('ModeFamily:SweepPointFailed', ...
            'Sweep point %d failed: %s', jj, ME.message);

        fprintf('  failed. time = %.2f s\n', toc(tStart));
        fprintf('  Error: %s\n\n', ME.message);
    end

    thisPoint = table( ...
        jj, ...
        w_um, ...
        success, ...
        numModes, ...
        numAccepted, ...
        toc(tStart), ...
        message, ...
        'VariableNames', { ...
            'sweep_index', ...
            'w_um', ...
            'success', ...
            'numModes', ...
            'numAccepted', ...
            'runtime_s', ...
            'message'});

    pointSummaryTable = [pointSummaryTable; thisPoint]; %#ok<AGROW>

    if cfg.saveAfterEachSweepPoint
        save(fullfile(cfg.outputDir, 'mode_family_raw.mat'), ...
            'cfg', 'allModeTable', 'acceptedModeTable', ...
            'pointSummaryTable');
    end
end

%% ===================== 6. Save final results =====================
rawMatFile = fullfile(cfg.outputDir, 'mode_family_raw.mat');
acceptedCsvFile = fullfile(cfg.outputDir, 'mode_family_metrics.csv');
allCsvFile = fullfile(cfg.outputDir, 'mode_family_all_modes.csv');
summaryCsvFile = fullfile(cfg.outputDir, 'sweep_point_summary.csv');

save(rawMatFile, ...
    'cfg', 'allModeTable', 'acceptedModeTable', 'pointSummaryTable');

writetable(acceptedModeTable, acceptedCsvFile);

if cfg.saveAllModesCsv
    writetable(allModeTable, allCsvFile);
end

writetable(pointSummaryTable, summaryCsvFile);

fprintf('\nMode-family component-ratio sweep finished.\n');
fprintf('Raw MAT file:\n  %s\n', rawMatFile);
fprintf('Accepted-mode metrics CSV:\n  %s\n', acceptedCsvFile);

if cfg.saveAllModesCsv
    fprintf('All-mode CSV:\n  %s\n', allCsvFile);
end

fprintf('Point summary CSV:\n  %s\n', summaryCsvFile);

%% ===================== Local helper functions =====================
function model = ensure_mode_family_variables(model, cfg)
%ENSURE_MODE_FAMILY_VARIABLES Create or update COMSOL variables.

    comp = model.component(cfg.componentTag);

    try
        comp.variable(cfg.variableTag);
    catch
        comp.variable.create(cfg.variableTag);
    end

    varObj = comp.variable(cfg.variableTag);
    varObj.label(cfg.variableLabel);

    intop = cfg.intopName;

    varObj.set('mode_IEx', sprintf('%s(abs(%s)^2)', intop, cfg.ExExpr));
    varObj.set('mode_IEy', sprintf('%s(abs(%s)^2)', intop, cfg.EyExpr));
    varObj.set('mode_IEz', sprintf('%s(abs(%s)^2)', intop, cfg.EzExpr));

    varObj.set('mode_Ixy',  'mode_IEx + mode_IEy');
    varObj.set('mode_Ixyz', 'mode_IEx + mode_IEy + mode_IEz');

    varObj.set('mode_Ex_frac_xy',  'mode_IEx/mode_Ixy');
    varObj.set('mode_Ey_frac_xy',  'mode_IEy/mode_Ixy');
    varObj.set('mode_Ex_frac_xyz', 'mode_IEx/mode_Ixyz');
    varObj.set('mode_Ey_frac_xyz', 'mode_IEy/mode_Ixyz');
    varObj.set('mode_Ez_frac_xyz', 'mode_IEz/mode_Ixyz');

    fprintf('Created/updated COMSOL variable group: %s\n', ...
        cfg.variableTag);
end

function T = read_mode_family_table(model, cfg, sweepIndex, w_um)
%READ_MODE_FAMILY_TABLE Read all mode-family scalar metrics.

    neffAll = read_global_all_modes(model, cfg, cfg.neffExpr);
    IExAll  = read_global_all_modes(model, cfg, 'mode_IEx');
    IEyAll  = read_global_all_modes(model, cfg, 'mode_IEy');
    IEzAll  = read_global_all_modes(model, cfg, 'mode_IEz');

    neffAll = neffAll(:);
    IExAll = real(IExAll(:));
    IEyAll = real(IEyAll(:));
    IEzAll = real(IEzAll(:));

    numModes = numel(neffAll);

    validate_same_length(numModes, IExAll, 'mode_IEx');
    validate_same_length(numModes, IEyAll, 'mode_IEy');
    validate_same_length(numModes, IEzAll, 'mode_IEz');

    [lossAll, qEstAll] = neff_to_loss_and_q(neffAll, cfg.lambda0_um);

    T = make_mode_family_table_for_one_width( ...
        sweepIndex, w_um, neffAll, lossAll, qEstAll, ...
        IExAll, IEyAll, IEzAll, cfg);
end

function value = read_global_all_modes(model, cfg, expr)
%READ_GLOBAL_ALL_MODES Read one global expression for all mode solutions.

    value = mphglobal(model, expr, ...
        'dataset', cfg.datasetTag, ...
        'solnum', 'all', ...
        'Complexout', 'on');
end

function validate_same_length(numModes, value, exprName)
%VALIDATE_SAME_LENGTH Check expression result length.

    if numel(value) ~= numModes
        error('ModeFamily:ExpressionLengthMismatch', ...
            ['Expression "%s" returned %d values, but ewfd.neff ', ...
             'returned %d modes. Check dataset, solnum, and variable ', ...
             'definition.'], ...
            exprName, numel(value), numModes);
    end
end

function [loss_dB_per_cm, Q_est] = neff_to_loss_and_q(neff, lambda0_um)
%NEFF_TO_LOSS_AND_Q Convert imag(neff) to loss and Q-like metric.

    lambda0_m = lambda0_um * 1e-6;
    k0 = 2*pi/lambda0_m;

    alpha_power_per_m = 2*k0*abs(imag(neff));
    loss_dB_per_m = 10*log10(exp(1)) * alpha_power_per_m;
    loss_dB_per_cm = loss_dB_per_m / 100;

    denom = 2*abs(imag(neff));
    Q_est = real(neff) ./ denom;
    Q_est(denom == 0) = Inf;
end

function isAccepted = apply_bound_mode_filter(neffAll, lossAll, qEstAll, cfg)
%APPLY_BOUND_MODE_FILTER Select usable bound modes.

    isAccepted = isfinite(real(neffAll)) & isfinite(imag(neffAll));

    if cfg.useLossThreshold
        isAccepted = isAccepted & (lossAll <= cfg.maxLoss_dB_per_cm);
    end

    if cfg.useQThreshold
        isAccepted = isAccepted & (qEstAll >= cfg.minQ_est);
    end

    isAccepted = isAccepted(:);
end

function T = make_mode_family_table_for_one_width( ...
    sweepIndex, w_um, neffAll, lossAll, qEstAll, ...
    IExAll, IEyAll, IEzAll, cfg)
%MAKE_MODE_FAMILY_TABLE_FOR_ONE_WIDTH Build table rows.

    numModes = numel(neffAll);

    Ixy = IExAll + IEyAll;
    Ixyz = IExAll + IEyAll + IEzAll;

    Ex_frac_xy  = safe_divide_vector(IExAll, Ixy);
    Ey_frac_xy  = safe_divide_vector(IEyAll, Ixy);
    Ex_frac_xyz = safe_divide_vector(IExAll, Ixyz);
    Ey_frac_xyz = safe_divide_vector(IEyAll, Ixyz);
    Ez_frac_xyz = safe_divide_vector(IEzAll, Ixyz);

    familyLabel = strings(numModes, 1);

    for mm = 1:numModes
        if Ex_frac_xy(mm) >= cfg.minDominantFraction
            familyLabel(mm) = "Ex_dominant";
        elseif Ey_frac_xy(mm) >= cfg.minDominantFraction
            familyLabel(mm) = "Ey_dominant";
        else
            familyLabel(mm) = "hybrid_xy";
        end
    end

    T = table( ...
        repmat(sweepIndex, numModes, 1), ...
        repmat(w_um, numModes, 1), ...
        (1:numModes).', ...
        real(neffAll(:)), ...
        imag(neffAll(:)), ...
        lossAll(:), ...
        qEstAll(:), ...
        IExAll(:), ...
        IEyAll(:), ...
        IEzAll(:), ...
        Ixy(:), ...
        Ixyz(:), ...
        Ex_frac_xy(:), ...
        Ey_frac_xy(:), ...
        Ex_frac_xyz(:), ...
        Ey_frac_xyz(:), ...
        Ez_frac_xyz(:), ...
        familyLabel(:), ...
        'VariableNames', { ...
            'sweep_index', ...
            'w_um', ...
            'mode_index', ...
            'neff_real', ...
            'neff_imag', ...
            'loss_dB_per_cm', ...
            'Q_est', ...
            'IEx', ...
            'IEy', ...
            'IEz', ...
            'Ixy', ...
            'Ixyz', ...
            'Ex_frac_xy', ...
            'Ey_frac_xy', ...
            'Ex_frac_xyz', ...
            'Ey_frac_xyz', ...
            'Ez_frac_xyz', ...
            'family_label'});
end

function y = safe_divide_vector(a, b)
%SAFE_DIVIDE_VECTOR Element-wise division with NaN for zero denominators.

    y = NaN(size(a));
    valid = isfinite(a) & isfinite(b) & (b ~= 0);
    y(valid) = a(valid) ./ b(valid);
end
