%% LiveLink Module 05B: Overlap extraction near mode crossing
% This is a COMSOL-run / field-extraction script. It does NOT make figures.
% Post-processing: use livelink_mode_family_overlap_postprocess.m.

clear; clc; close all;

%% ===================== 1. User configuration =====================
thisFile = mfilename('fullpath');
if isempty(thisFile)
    templateDir = pwd;
else
    templateDir = fileparts(thisFile);
end
repoRoot = fileparts(templateDir);

cfg = struct();
cfg.modelFile    = fullfile(repoRoot, 'examples', 'LN_ridge_waveguide_Zcut.mph');
cfg.componentTag = 'comp1';
cfg.studyTag     = 'std1';
cfg.datasetTag   = 'dset1';

% Two parameter values to compare
cfg.paramName = 'w_ln';
cfg.paramUnit = 'um';
cfg.widthPrev_um = 1.0;
cfg.widthCurr_um = 1.05;

% Number of solved modes
cfg.setNmodeParam = true;
cfg.NmodeParamName = 'Nmode';
cfg.Nmode = 10;

% Optical wavelength and filtering
cfg.lambda0_um = 1.55;
cfg.useLossThreshold  = true;
cfg.maxLoss_dB_per_cm = 10;
cfg.useQThreshold = false;
cfg.minQ_est      = 1e5;
cfg.onlyOverlapAcceptedModes = true;

% COMSOL expressions and LiveLink-defined variables
cfg.neffExpr = 'ewfd.neff';
cfg.ExExpr = 'ewfd.Ex';
cfg.EyExpr = 'ewfd.Ey';
cfg.EzExpr = 'ewfd.Ez';
cfg.fieldExprList = {'ewfd.Ex', 'ewfd.Ey', 'ewfd.Ez'};
cfg.componentNames = {'Ex', 'Ey', 'Ez'};
cfg.intopName = 'intop_LN_physical';
cfg.variableTag   = 'var_mode_family';
cfg.variableLabel = 'Mode-family metrics generated by MATLAB LiveLink';
cfg.minDominantFraction = 0.80;

% Interpolation grid for overlap. Lists are in um, passed to COMSOL in m.
cfg.xList_um = linspace(-1.5, 1.5, 241);
cfg.yList_um = linspace(-0.2, 1.2, 181);
cfg.coordScaleToModel = 1e-6;
cfg.coordScaleToMeter = 1e-6;
cfg.useRectMask = false;
cfg.maskX_um = [-1.5, 1.5];
cfg.maskY_um = [-0.2, 1.2];

% Output
cfg.outputRoot = fullfile(repoRoot, 'local_outputs');
timestamp = char(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
cfg.runName = ['mode_family_overlap_check_', timestamp];
cfg.outputDir = fullfile(cfg.outputRoot, cfg.runName);

%% ===================== 2. Prepare output folder =====================
if ~exist(cfg.outputDir, 'dir')
    mkdir(cfg.outputDir);
end
save(fullfile(cfg.outputDir, 'overlap_config.mat'), 'cfg');

%% ===================== 3. Load COMSOL model =====================
if exist(cfg.modelFile, 'file') ~= 2
    error('ModeFamily:ModelFileNotFound', ...
        ['COMSOL model file not found:\n  %s\n\n', ...
         'Please update cfg.modelFile.'], cfg.modelFile);
end

fprintf('Loading COMSOL model:\n  %s\n', cfg.modelFile);
model = mphload(cfg.modelFile);
model = ensure_mode_family_variables(model, cfg);

if cfg.setNmodeParam
    model.param.set(cfg.NmodeParamName, sprintf('%d', cfg.Nmode));
    fprintf('Set number-of-modes parameter: %s = %d\n', ...
        cfg.NmodeParamName, cfg.Nmode);
end

grid = make_interpolation_grid(cfg);

%% ===================== 4. Solve points and extract fields =====================
fprintf('\nSolving previous parameter point: %.6g %s\n', ...
    cfg.widthPrev_um, cfg.paramUnit);
prevData = solve_filter_and_extract_fields(model, cfg, grid, cfg.widthPrev_um, "previous");

fprintf('\nSolving current parameter point: %.6g %s\n', ...
    cfg.widthCurr_um, cfg.paramUnit);
currData = solve_filter_and_extract_fields(model, cfg, grid, cfg.widthCurr_um, "current");

%% ===================== 5. Compute overlap matrix =====================
numPrev = numel(prevData.selectedModeIndex);
numCurr = numel(currData.selectedModeIndex);

overlapMatrix = NaN(numPrev, numCurr);
pairTable = table();

for mm = 1:numPrev
    for nn = 1:numCurr
        O = normalized_field_overlap(prevData.fields{mm}, currData.fields{nn}, grid);
        overlapMatrix(mm, nn) = O;

        prevRow = prevData.selectedTable(mm, :);
        currRow = currData.selectedTable(nn, :);

        thisRow = table( ...
            prevRow.mode_index, currRow.mode_index, ...
            prevRow.neff_real, currRow.neff_real, ...
            prevRow.loss_dB_per_cm, currRow.loss_dB_per_cm, ...
            prevRow.Ex_frac_xy, currRow.Ex_frac_xy, ...
            string(prevRow.family_label), string(currRow.family_label), ...
            O, ...
            'VariableNames', { ...
                'prev_mode_index', 'curr_mode_index', ...
                'prev_neff_real', 'curr_neff_real', ...
                'prev_loss_dB_per_cm', 'curr_loss_dB_per_cm', ...
                'prev_Ex_frac_xy', 'curr_Ex_frac_xy', ...
                'prev_family_label', 'curr_family_label', ...
                'overlap'});
        pairTable = [pairTable; thisRow]; %#ok<AGROW>
    end
end

bestMatchTable = make_best_match_table(prevData, currData, overlapMatrix);

%% ===================== 6. Save results =====================
rawMatFile = fullfile(cfg.outputDir, 'overlap_raw.mat');
pairCsvFile = fullfile(cfg.outputDir, 'overlap_pairs.csv');
matrixCsvFile = fullfile(cfg.outputDir, 'overlap_matrix.csv');
bestMatchCsvFile = fullfile(cfg.outputDir, 'overlap_best_matches.csv');
prevCsvFile = fullfile(cfg.outputDir, 'previous_modes.csv');
currCsvFile = fullfile(cfg.outputDir, 'current_modes.csv');

save(rawMatFile, 'cfg', 'prevData', 'currData', 'overlapMatrix', ...
    'pairTable', 'bestMatchTable');
writetable(pairTable, pairCsvFile);
writematrix(overlapMatrix, matrixCsvFile);
writetable(bestMatchTable, bestMatchCsvFile);
writetable(prevData.selectedTable, prevCsvFile);
writetable(currData.selectedTable, currCsvFile);

fprintf('\nOverlap extraction finished.\n');
fprintf('Raw MAT file:\n  %s\n', rawMatFile);
fprintf('Pairwise overlap table:\n  %s\n', pairCsvFile);
fprintf('Overlap matrix:\n  %s\n', matrixCsvFile);
fprintf('Best-match table:\n  %s\n', bestMatchCsvFile);

%% ===================== Local helper functions =====================
function model = ensure_mode_family_variables(model, cfg)
    comp = model.component(cfg.componentTag);
    try
        comp.variable(cfg.variableTag);
    catch
        comp.variable.create(cfg.variableTag);
    end
    varObj = comp.variable(cfg.variableTag);
    varObj.label(cfg.variableLabel);
    intop = cfg.intopName;
    varObj.set('mode_IEx', sprintf('%s(abs(%s)^2)', intop, cfg.ExExpr));
    varObj.set('mode_IEy', sprintf('%s(abs(%s)^2)', intop, cfg.EyExpr));
    varObj.set('mode_IEz', sprintf('%s(abs(%s)^2)', intop, cfg.EzExpr));
    varObj.set('mode_Ixy',  'mode_IEx + mode_IEy');
    varObj.set('mode_Ixyz', 'mode_IEx + mode_IEy + mode_IEz');
    varObj.set('mode_Ex_frac_xy',  'mode_IEx/mode_Ixy');
    varObj.set('mode_Ey_frac_xy',  'mode_IEy/mode_Ixy');
    varObj.set('mode_Ex_frac_xyz', 'mode_IEx/mode_Ixyz');
    varObj.set('mode_Ey_frac_xyz', 'mode_IEy/mode_Ixyz');
    varObj.set('mode_Ez_frac_xyz', 'mode_IEz/mode_Ixyz');
end

function grid = make_interpolation_grid(cfg)
    [X_um, Y_um] = meshgrid(cfg.xList_um, cfg.yList_um);
    coord = cfg.coordScaleToModel * [X_um(:).'; Y_um(:).'];
    if cfg.useRectMask
        mask = X_um >= cfg.maskX_um(1) & X_um <= cfg.maskX_um(2) & ...
               Y_um >= cfg.maskY_um(1) & Y_um <= cfg.maskY_um(2);
    else
        mask = true(size(X_um));
    end
    grid = struct();
    grid.X_um = X_um;
    grid.Y_um = Y_um;
    grid.x_m = cfg.coordScaleToMeter * cfg.xList_um(:).';
    grid.y_m = cfg.coordScaleToMeter * cfg.yList_um(:);
    grid.coord = coord;
    grid.mask = mask;
end

function data = solve_filter_and_extract_fields(model, cfg, grid, width_um, label)
    if cfg.setNmodeParam
        model.param.set(cfg.NmodeParamName, sprintf('%d', cfg.Nmode));
    end
    model.param.set(cfg.paramName, sprintf('%.12g[%s]', width_um, cfg.paramUnit));
    model.study(cfg.studyTag).run;
    allTable = read_mode_family_table(model, cfg, 1, width_um);
    allTable.isAccepted = apply_bound_mode_filter( ...
        allTable.neff_real + 1i*allTable.neff_imag, ...
        allTable.loss_dB_per_cm, allTable.Q_est, cfg);
    if cfg.onlyOverlapAcceptedModes
        selectedTable = allTable(allTable.isAccepted, :);
    else
        selectedTable = allTable;
    end
    selectedModeIndex = selectedTable.mode_index;
    fprintf('  %s width: %.6g %s\n', label, width_um, cfg.paramUnit);
    fprintf('  returned modes: %d\n', height(allTable));
    fprintf('  selected modes for overlap: %d\n', height(selectedTable));
    fields = cell(height(selectedTable), 1);
    for kk = 1:height(selectedTable)
        fields{kk} = extract_mode_fields(model, cfg, grid, selectedModeIndex(kk));
    end
    data = struct();
    data.width_um = width_um;
    data.allTable = allTable;
    data.selectedTable = selectedTable;
    data.selectedModeIndex = selectedModeIndex;
    data.fields = fields;
end

function T = read_mode_family_table(model, cfg, sweepIndex, w_um)
    neffAll = read_global_all_modes(model, cfg, cfg.neffExpr);
    IExAll  = read_global_all_modes(model, cfg, 'mode_IEx');
    IEyAll  = read_global_all_modes(model, cfg, 'mode_IEy');
    IEzAll  = read_global_all_modes(model, cfg, 'mode_IEz');
    neffAll = neffAll(:);
    IExAll = real(IExAll(:));
    IEyAll = real(IEyAll(:));
    IEzAll = real(IEzAll(:));
    [lossAll, qEstAll] = neff_to_loss_and_q(neffAll, cfg.lambda0_um);
    T = make_mode_family_table_for_one_width(sweepIndex, w_um, neffAll, ...
        lossAll, qEstAll, IExAll, IEyAll, IEzAll, cfg);
end

function value = read_global_all_modes(model, cfg, expr)
    value = mphglobal(model, expr, 'dataset', cfg.datasetTag, ...
        'solnum', 'all', 'Complexout', 'on');
end

function [loss_dB_per_cm, Q_est] = neff_to_loss_and_q(neff, lambda0_um)
    lambda0_m = lambda0_um * 1e-6;
    k0 = 2*pi/lambda0_m;
    alpha_power_per_m = 2*k0*abs(imag(neff));
    loss_dB_per_m = 10*log10(exp(1)) * alpha_power_per_m;
    loss_dB_per_cm = loss_dB_per_m / 100;
    denom = 2*abs(imag(neff));
    Q_est = real(neff) ./ denom;
    Q_est(denom == 0) = Inf;
end

function isAccepted = apply_bound_mode_filter(neffAll, lossAll, qEstAll, cfg)
    isAccepted = isfinite(real(neffAll)) & isfinite(imag(neffAll));
    if cfg.useLossThreshold
        isAccepted = isAccepted & (lossAll <= cfg.maxLoss_dB_per_cm);
    end
    if cfg.useQThreshold
        isAccepted = isAccepted & (qEstAll >= cfg.minQ_est);
    end
    isAccepted = isAccepted(:);
end

function T = make_mode_family_table_for_one_width(sweepIndex, w_um, neffAll, ...
    lossAll, qEstAll, IExAll, IEyAll, IEzAll, cfg)
    numModes = numel(neffAll);
    Ixy = IExAll + IEyAll;
    Ixyz = IExAll + IEyAll + IEzAll;
    Ex_frac_xy  = safe_divide_vector(IExAll, Ixy);
    Ey_frac_xy  = safe_divide_vector(IEyAll, Ixy);
    Ex_frac_xyz = safe_divide_vector(IExAll, Ixyz);
    Ey_frac_xyz = safe_divide_vector(IEyAll, Ixyz);
    Ez_frac_xyz = safe_divide_vector(IEzAll, Ixyz);
    familyLabel = strings(numModes, 1);
    for mm = 1:numModes
        if Ex_frac_xy(mm) >= cfg.minDominantFraction
            familyLabel(mm) = "Ex_dominant";
        elseif Ey_frac_xy(mm) >= cfg.minDominantFraction
            familyLabel(mm) = "Ey_dominant";
        else
            familyLabel(mm) = "hybrid_xy";
        end
    end
    T = table(repmat(sweepIndex, numModes, 1), repmat(w_um, numModes, 1), ...
        (1:numModes).', real(neffAll(:)), imag(neffAll(:)), lossAll(:), ...
        qEstAll(:), IExAll(:), IEyAll(:), IEzAll(:), Ixy(:), Ixyz(:), ...
        Ex_frac_xy(:), Ey_frac_xy(:), Ex_frac_xyz(:), Ey_frac_xyz(:), ...
        Ez_frac_xyz(:), familyLabel(:), ...
        'VariableNames', {'sweep_index','w_um','mode_index','neff_real', ...
        'neff_imag','loss_dB_per_cm','Q_est','IEx','IEy','IEz','Ixy', ...
        'Ixyz','Ex_frac_xy','Ey_frac_xy','Ex_frac_xyz','Ey_frac_xyz', ...
        'Ez_frac_xyz','family_label'});
end

function y = safe_divide_vector(a, b)
    y = NaN(size(a));
    valid = isfinite(a) & isfinite(b) & (b ~= 0);
    y(valid) = a(valid) ./ b(valid);
end

function fieldStruct = extract_mode_fields(model, cfg, grid, solnum)
    fieldStruct = struct();
    for kk = 1:numel(cfg.fieldExprList)
        expr = cfg.fieldExprList{kk};
        name = cfg.componentNames{kk};
        raw = mphinterp(model, expr, 'coord', grid.coord, ...
            'dataset', cfg.datasetTag, 'solnum', solnum, 'Complexout', 'on');
        fieldStruct.(name) = reshape(raw, size(grid.X_um));
    end
end

function O = normalized_field_overlap(fieldA, fieldB, grid)
    componentList = intersect(fieldnames(fieldA), fieldnames(fieldB));
    numeratorDensity = zeros(size(grid.X_um));
    normADensity = zeros(size(grid.X_um));
    normBDensity = zeros(size(grid.X_um));
    for kk = 1:numel(componentList)
        name = componentList{kk};
        EA = fieldA.(name);
        EB = fieldB.(name);
        numeratorDensity = numeratorDensity + conj(EA).*EB;
        normADensity = normADensity + abs(EA).^2;
        normBDensity = normBDensity + abs(EB).^2;
    end
    numerator = integrate2(numeratorDensity, grid);
    normA = integrate2(normADensity, grid);
    normB = integrate2(normBDensity, grid);
    if normA <= 0 || normB <= 0
        O = NaN;
    else
        O = abs(numerator)^2 / (normA * normB);
    end
end

function value = integrate2(Z, grid)
    Zmasked = Z;
    Zmasked(~grid.mask) = 0;
    value = trapz(grid.y_m, trapz(grid.x_m, Zmasked, 2));
end

function T = make_best_match_table(prevData, currData, overlapMatrix)
    numPrev = size(overlapMatrix, 1);
    prevModeIndex = NaN(numPrev, 1);
    bestCurrModeIndex = NaN(numPrev, 1);
    bestOverlap = NaN(numPrev, 1);
    prevNeffReal = NaN(numPrev, 1);
    bestCurrNeffReal = NaN(numPrev, 1);
    prevFamilyLabel = strings(numPrev, 1);
    bestCurrFamilyLabel = strings(numPrev, 1);
    for mm = 1:numPrev
        prevModeIndex(mm) = prevData.selectedTable.mode_index(mm);
        prevNeffReal(mm) = prevData.selectedTable.neff_real(mm);
        prevFamilyLabel(mm) = string(prevData.selectedTable.family_label(mm));
        [bestOverlap(mm), idx] = max(overlapMatrix(mm, :));
        if ~isempty(idx) && isfinite(bestOverlap(mm))
            bestCurrModeIndex(mm) = currData.selectedTable.mode_index(idx);
            bestCurrNeffReal(mm) = currData.selectedTable.neff_real(idx);
            bestCurrFamilyLabel(mm) = string(currData.selectedTable.family_label(idx));
        end
    end
    T = table(prevModeIndex, bestCurrModeIndex, bestOverlap, ...
        prevNeffReal, bestCurrNeffReal, prevFamilyLabel, bestCurrFamilyLabel, ...
        'VariableNames', {'prev_mode_index','best_curr_mode_index', ...
        'best_overlap','prev_neff_real','best_curr_neff_real', ...
        'prev_family_label','best_curr_family_label'});
end
